/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ReflectionRouteImport } from './routes/reflection'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as DeliverablesRouteImport } from './routes/deliverables'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as IndexRouteImport } from './routes/index'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectionRoute = ReflectionRouteImport.update({
  id: '/reflection',
  path: '/reflection',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverablesRoute = DeliverablesRouteImport.update({
  id: '/deliverables',
  path: '/deliverables',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/deliverables': typeof DeliverablesRoute
  '/development': typeof DevelopmentRoute
  '/profile': typeof ProfileRoute
  '/project': typeof ProjectRoute
  '/reflection': typeof ReflectionRoute
  '/solutions': typeof SolutionsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/deliverables': typeof DeliverablesRoute
  '/development': typeof DevelopmentRoute
  '/profile': typeof ProfileRoute
  '/project': typeof ProjectRoute
  '/reflection': typeof ReflectionRoute
  '/solutions': typeof SolutionsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/deliverables': typeof DeliverablesRoute
  '/development': typeof DevelopmentRoute
  '/profile': typeof ProfileRoute
  '/project': typeof ProjectRoute
  '/reflection': typeof ReflectionRoute
  '/solutions': typeof SolutionsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/deliverables'
    | '/development'
    | '/profile'
    | '/project'
    | '/reflection'
    | '/solutions'
    | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/deliverables'
    | '/development'
    | '/profile'
    | '/project'
    | '/reflection'
    | '/solutions'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/deliverables'
    | '/development'
    | '/profile'
    | '/project'
    | '/reflection'
    | '/solutions'
    | '/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  DeliverablesRoute: typeof DeliverablesRoute
  DevelopmentRoute: typeof DevelopmentRoute
  ProfileRoute: typeof ProfileRoute
  ProjectRoute: typeof ProjectRoute
  ReflectionRoute: typeof ReflectionRoute
  SolutionsRoute: typeof SolutionsRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflection': {
      id: '/reflection'
      path: '/reflection'
      fullPath: '/reflection'
      preLoaderRoute: typeof ReflectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliverables': {
      id: '/deliverables'
      path: '/deliverables'
      fullPath: '/deliverables'
      preLoaderRoute: typeof DeliverablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  DeliverablesRoute: DeliverablesRoute,
  DevelopmentRoute: DevelopmentRoute,
  ProfileRoute: ProfileRoute,
  ProjectRoute: ProjectRoute,
  ReflectionRoute: ReflectionRoute,
  SolutionsRoute: SolutionsRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
